### ISSUE TITLE
-- comment crash pgtyped

### ISSUE THREAD

**Issue by darky** [adelsz/pgtyped#176]
Example:

```sql
      /* ts-sql-plugin:emit("Subscription") */
      /* @name Subscription */
      SELECT sub.*
      FROM (
  -- ts-sql-plugin:ignore-cost
  SELECT *
  FROM test
  WHERE test = null
  ) sub
      WHERE test = null;
```

Crash:

```
1|pgtyped  | Error processing file: TypeError: Cannot read property 'name' of undefined
1|pgtyped  |     at TypeAllocator.use (/Users/vladislavbotvin/Projects/test/node_modules/@pgtyped/cli/lib/types.js:117:24)
1|pgtyped  |     at /Users/vladislavbotvin/Projects/test/node_modules/@pgtyped/cli/lib/generator.js:74:40
1|pgtyped  |     at Generator.next (<anonymous>)
1|pgtyped  |     at fulfilled (/Users/vladislavbotvin/Projects/test/node_modules/@pgtyped/cli/lib/generator.js:5:58)
1|pgtyped  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by adelsz** [comment]
No longer reproducible, closing.
