### ISSUE TITLE
Error: Postgres type 'tstzrange' is not supported by mapping when trying to insert an array of values

### ISSUE THREAD

**Issue by bag-man** [adelsz/pgtyped#213]
I'm trying to insert an array of values into a table that contains a column with the tstzrange type. I was able to insert a single value by constructing the range in the SQL like so:

```
INSERT INTO times (id, period) VALUES (:id, tstzrange(:start, :end, '[)'));
```

But is it possible to do it with an array of values? Here is my setup.

```
CREATE TABLE IF NOT EXISTS times (
  id uuid DEFAULT uuid_generate_v4(),
  period tstzrange NOT NULL,

  PRIMARY KEY (id)
);
```

```
/* 
  @name createTimes
  @param times -> ((id, period)...)
*/
INSERT INTO times (id, period) VALUES :times;
```

```
Error: Postgres type 'tstzrange' is not supported by mapping
    at TypeAllocator.use (/home/owg1/Projects/book-svc/node_modules/@pgtyped/cli/lib/types.js:108:34)
    at /home/owg1/Projects/book-svc/node_modules/@pgtyped/cli/lib/generator.js:85:45
    at Array.map (<anonymous>)
    at /home/owg1/Projects/book-svc/node_modules/@pgtyped/cli/lib/generator.js:84:22
    at Generator.next (<anonymous>)
    at fulfilled (/home/owg1/Projects/book-svc/node_modules/@pgtyped/cli/lib/generator.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

**Comment by theswerd** [comment]
+1
