### ISSUE TITLE
bug: array input not injected

### ISSUE THREAD

**Issue by wongjiahau** [adelsz/pgtyped#311]
## Version
```
0.11
```

## Input
```sql
/*                                                                                                              
 @name findTransactionCommissionPaymentSlipsByInvoiceIds                                                        
 @param transaction_commission_invoice_ids -> (...)
*/                                                                                                             
SELECT                                                                                                          
  *                                                                                                           
FROM                                                                                                            
  transaction_commission_payment_slip_invoice i                                                  
WHERE                                                                                                           
  i.transaction_commission_invoice_id IN :transaction_commission_invoice_ids;                                  
```

## Generated SQL
```sql
SELECT                                                                                                    
  *                                                                                                     
FROM                                                                                                      
  transaction_commission_payment_slip_invoice i                                                           
WHERE                                                                                                     
  i.transaction_commission_invoice_id IN ()                                                               
```
Bindings:
```json                                                                                                         
{                                                                                                         
  "bindings": []                                                                                          
}                                                                                                         
```
Postgres errors:
```
error: syntax error at or near ")"                                                               
    at Parser.parseErrorMessage (/didian-client-api/node_modules/pg-protocol/dist/parser.js:287:98)       
    at Parser.handlePacket (/didian-client-api/node_modules/pg-protocol/dist/parser.js:126:29)            
    at Parser.parse (/didian-client-api/node_modules/pg-protocol/dist/parser.js:39:38)                    
    at Socket.<anonymous> (/didian-client-api/node_modules/pg-protocol/dist/index.js:11:42)               
    at Socket.emit (events.js:400:28)                                                                     
    at Socket.emit (domain.js:470:12)                                                                     
    at addChunk (internal/streams/readable.js:290:12)                                                     
    at readableAddChunk (internal/streams/readable.js:265:9)                                              
    at Socket.Readable.push (internal/streams/readable.js:204:10)                                         
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by wongjiahau** [comment]
Related to #221
