### ISSUE TITLE
JSON Array as input for `jsonb_set` fails

### ISSUE THREAD

**Issue by bryanjswift** [adelsz/pgtyped#497]
**Describe the bug**

I have a query that accepts `Json` as one of its parameters.

```sql
/*
 @name SiteUpdateCertificateVerification
 */
UPDATE site
SET
  "settings" = jsonb_set(
    site."settings",
    '{certificateVerification}',
    :certificateVerification!,
    true
  )
WHERE site."id" = :siteId!
RETURNING *
;
```

When this is passed a JSON array I get the following error:

```json
{
  "errorType": "error",
  "errorMessage": "invalid input syntax for type json",
  "code": "22P02",
  "length": 202,
  "name": "error",
  "severity": "ERROR",
  "detail": "Expected \":\", but found \",\".",
  "where": "JSON data, line 1: ...3902de6be949.xyscsmcmgv.acm-validations.aws.\\\"}\",...",
  "file": "json.c",
  "line": "1203",
  "routine": "report_parse_error",
  "stack": [
    "error: invalid input syntax for type json",
    "    at Parser.parseErrorMessage (/opt/nodejs/node_modules/pg-protocol/dist/parser.js:287:98)",
    "    at Parser.handlePacket (/opt/nodejs/node_modules/pg-protocol/dist/parser.js:126:29)",
    "    at Parser.parse (/opt/nodejs/node_modules/pg-protocol/dist/parser.js:39:38)",
    "    at Socket.<anonymous> (/opt/nodejs/node_modules/pg-protocol/dist/index.js:11:42)",
    "    at Socket.emit (node:events:527:28)",
    "    at addChunk (node:internal/streams/readable:315:12)",
    "    at readableAddChunk (node:internal/streams/readable:289:9)",
    "    at Socket.Readable.push (node:internal/streams/readable:228:10)",
    "    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
    "    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)"
  ]
}
```

**Expected behavior**

I expected passing valid JSON to work with `jsonb_set`.

**Test case**

Apologies for not creating the example test case. I'll revisit if I have some spare time later this week. Below is the schema of the site table.

```sql
create table public.site
(
    id               uuid      default gen_random_uuid() not null
        primary key,
    name             text                                not null,
    "organizationID" uuid                                not null
        references public.organization,
    variables        jsonb,
    "createdAt"      timestamp default now()             not null,
    "updatedAt"      timestamp default now()             not null,
    meta             jsonb     default '{}'::jsonb       not null,
    resources        jsonb     default '[]'::jsonb       not null,
    status           text      default 'active'::text    not null
        constraint status
            check (status = ANY (ARRAY ['active'::text, 'archived'::text])),
    css              text      default ''::text          not null
);

comment on column public.site.css is 'Site-wide CSS to add to every page';

alter table public.site
    owner to postgres;

create unique index "site_organizationID_name_idx"
    on public.site ("organizationID", name);

```

**Comment by bryanjswift** [comment]
I think I must have been doing something wrong. I just tried this again and it worked as expected.
