### ISSUE TITLE
PG array types are unsupported

### ISSUE THREAD

**Issue by shkarpa** [adelsz/pgtyped#95]
I've set up pgtyped without any problems, but I have a column in my table of type `character varying(100)[]` or `varchar(100)[]`. Upon running pgtyped CLI, I get the following error: 
```
Error: Postgres type '_varchar' is not supported by mapping
    at TypeAllocator.use (/home/mark/Work/configurator-sdk/node_modules/@pgtyped/cli/lib/types.js:99:34)
    at /home/mark/Work/configurator-sdk/node_modules/@pgtyped/cli/lib/generator.js:54:36
    at Array.forEach (<anonymous>)
    at /home/mark/Work/configurator-sdk/node_modules/@pgtyped/cli/lib/generator.js:53:21
    at Generator.next (<anonymous>)
    at fulfilled (/home/mark/Work/configurator-sdk/node_modules/@pgtyped/cli/lib/generator.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

and the column gets a type of `never` in the resulting `.ts` file. Would be great to add support for this kind of types in the future!

**Comment by adelsz** [comment]
Thanks @shkarpa!
We are aware of it and plan on adding it shortly.
That will require some tighter integration with a specific pg client like `node-postgres`, but it is planned.

**Comment by shkarpa** [comment]
@adelsz That is great news to hear! Thank you and good luck!

**Comment by Maxpain177** [comment]
Hello. Any updates on this?

**Comment by Maxpain177** [comment]
@adelsz

**Comment by Maxpain177** [comment]
@adelsz

**Comment by adelsz** [comment]
@Maxpain177 This is a bigger task and is a work in progress. I will update this thread once it is ready.

**Comment by steelbrain** [comment]
Can you please try the fix in https://github.com/adelsz/pgtyped/pull/172 and see if it works?

This is the patch for the latest release

```diff
diff --git a/node_modules/@pgtyped/cli/lib/types.js b/node_modules/@pgtyped/cli/lib/types.js
index 6e00c94..77256f3 100644
--- a/node_modules/@pgtyped/cli/lib/types.js
+++ b/node_modules/@pgtyped/cli/lib/types.js
@@ -12,6 +12,13 @@ const Json = {
     name: 'Json',
     definition: 'null | boolean | number | string | Json[] | { [key: string]: Json }',
 };
+const getArray = (baseType) => {
+    var _a;
+    return ({
+        name: `${baseType.name}Array`,
+        definition: `(${(_a = baseType.definition) !== null && _a !== void 0 ? _a : baseType.name})[]`,
+    });
+};
 exports.DefaultTypeMapping = Object.freeze({
     // Integer types
     int2: Number,
@@ -74,7 +81,7 @@ function declareAlias(name, definition) {
     return `export type ${name} = ${definition};\n`;
 }
 function declareStringUnion(name, values) {
-    return declareAlias(name, values.map(v => `'${v}'`).join(' | '));
+    return declareAlias(name, values.map((v) => `'${v}'`).join(' | '));
 }
 function declareEnum(name, values) {
     return `export const enum ${name} {\n${values
@@ -99,16 +106,27 @@ class TypeAllocator {
     /** Lookup a database-provided type name in the allocator's map */
     use(typeNameOrType) {
         var _a, _b;
-        let typ;
+        let typ = null;
         if (typeof typeNameOrType == 'string') {
-            if (!this.isMappedType(typeNameOrType)) {
-                if (this.allowUnmappedTypes) {
-                    return typeNameOrType;
+            if (typeNameOrType[0] === '_') {
+                // If starts with _ it is an PG Array type
+                const arrayValueType = typeNameOrType.slice(1);
+                // ^ Converts _varchar -> varchar, then wraps the type in an array
+                // type wrapper
+                if (this.isMappedType(arrayValueType)) {
+                    typ = getArray(this.mapping[arrayValueType]);
+                }
+            }
+            if (typ == null) {
+                if (!this.isMappedType(typeNameOrType)) {
+                    if (this.allowUnmappedTypes) {
+                        return typeNameOrType;
+                    }
+                    this.errors.push(new Error(`Postgres type '${typeNameOrType}' is not supported by mapping`));
+                    return 'never';
                 }
-                this.errors.push(new Error(`Postgres type '${typeNameOrType}' is not supported by mapping`));
-                return 'never';
+                typ = this.mapping[typeNameOrType];
             }
-            typ = this.mapping[typeNameOrType];
         }
         else {
             typ = typeNameOrType;
```

**Comment by thomasnaudin** [comment]
That would be really nice – I'd like to use params spread for UUIDs, which doesn't work atm.
